[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GNU KOR"
authors = [{name = "Hyun Seong, Kim", email = "qwqwhsnote@gm.gist.ac.kr"}]
dynamic = ["version", "description"]
